"""Architecture control: transformer vs GRU, everything else frozen.

This replaces the corpus x architecture 2x2, for two reasons found while
trying to run it.

**The corpus axis was near-vacuous.** ``build/dataset/build_report.json``
shows the published corpus was generated by this same repository from the
same generator. "Published corpus" against "regenerated from seeds" is
therefore a different draw from one distribution, not a different
distribution. With episode count matched at 200 it tests sampling noise. The
variable that actually differed in the quarantined claim was volume -- 3000
episodes against roughly 40 -- which is a separate experiment.

**The corpus arms were not comparable anyway.** The seeds path builds windows
in memory and validates on ``split(0.8)`` of those same episodes; the dataset
path streams windows and validates on a separate 178-episode corpus split,
with a different replay trace, class balancing and val stride. Average
precision computed on two different held-out sets is not one measurement, so
the "corpus effect" would have been corpus + pipeline + sampler + evaluation
set.

The architecture comparison has neither problem. Both arms take the same
``--episodes`` path, so they share the window construction, the split and the
held-out set exactly. Architecture is the only thing that differs, and it is
the question the shipping decision actually turns on.
"""

import json
import os
import pathlib
import subprocess
import time

T0 = time.time()

# `gru` is gone from this list deliberately. It won the accuracy comparison by
# ~9% AP and was disqualified by the latency gate -- 63.22 ms p99 decision on
# CPU and 3.12 ms on GPU against a 3.00 ms budget -- so re-running it would
# only re-measure a model that cannot ship. See reports/arch_latency.md.
#
# `tcn` replaces it because it is the only architecture that passes the gate
# and has never been measured for accuracy: 95,553 parameters, under a third
# of the transformer, at 1.69 ms p99 decision on GPU. Its dilated convolutions
# are parallel over time, so it carries none of the GRU's sequential penalty.
#
# STOP RULE: this is one controlled falsification check, not the start of an
# architecture search. TCN replaces the transformer only if it is both
# prediction-competitive AND viable in the deployment environment. It is 9.69
# ms on CPU, so a win here supports "TCN is a viable GPU-specific
# alternative" and nothing broader. If it loses, the architecture question is
# closed.
ARCHS = ("transformer", "tcn")

# ---- frozen ------------------------------------------------------------
TIER = os.environ.get("SMARTSCAN_TIER", "medium")
BATCH = 32          # pinned, NOT a ladder: batch 8 vs 64 moved AP 0.6915->0.7457
# The transformer's best epoch was 2 of 6 and validation AP fell monotonically
# after it (0.0693, 0.0605, 0.0592, 0.0573, 0.0572), so the later epochs bought
# overfitting and wall time. Cutting to 3 also brings the whole control inside
# Deepnote's detached-run limit, which killed an earlier attempt at 64.5 min
# with DETACHED_TIMEOUT_PREEMPTIBLE. Both arms take the same budget.
EPOCHS = 3
TEACHER_EPOCHS = 2
EPISODES = 200
WPE = 200
SEED = 0            # same episodes for both arms

REPO = "/root/ctlrepo"
OUT = "/work/arch_control_tcn_" + TIER
REPO_URL = "https://github.com/shirish-raj-gupta/SpectraX_Anveshak_SIH26055_Prototype"


def sh(cmd, check=True):
    """Run a shell command, streaming its output into the cell."""
    print("\n$ " + cmd, flush=True)
    rc = subprocess.run(cmd, shell=True).returncode
    print("  -> exit " + str(rc), flush=True)
    if rc and check:
        raise SystemExit("failed: " + cmd)
    return rc


# Only one copy at a time: Deepnote auto-runs the notebook on session
# creation, and two instances delete each other's working directory.
LOCK = pathlib.Path("/work/_jobs/archctl_tcn.lock")
LOCK.parent.mkdir(parents=True, exist_ok=True)
if LOCK.exists() and (time.time() - LOCK.stat().st_mtime) / 60 < 90:
    raise SystemExit(f"another instance holds {LOCK}")
LOCK.write_text(str(os.getpid()))

sh(f"rm -rf {REPO} && git clone -q {REPO_URL} {REPO}")
sh(f"git -C {REPO} log --oneline -1")
sh("python -m pip install -q torch --index-url "
   "https://download.pytorch.org/whl/cu121")
sh(f'python -m pip install -q -e "{REPO}[ml,viz]"')

import torch  # noqa: E402

print(f"\ntorch {torch.__version__} cuda={torch.cuda.is_available()} "
      f"{torch.cuda.get_device_name(0) if torch.cuda.is_available() else ''}",
      flush=True)
sh(f"mkdir -p {OUT}")

os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
results = {}
for arch in ARCHS:
    name = f"{TIER}-{arch}"
    print("\n" + "=" * 64)
    print(f"{name}   batch={BATCH} episodes={EPISODES} wpe={WPE} seed={SEED}")
    print("=" * 64, flush=True)
    t = time.time()
    rc = sh(
        f"cd {REPO} && PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True "
        f"python -m smartscan.cli train --config {TIER}.yaml --what predictor "
        f"--arch {arch} --episodes {EPISODES} --windows-per-episode {WPE} "
        f"--workers 8 --steps {EPOCHS} "
        f"--set run.seed={SEED} "
        f"--set predictor.batch_size={BATCH} "
        f"--set predictor.distillation.teacher_epochs={TEACHER_EPOCHS} "
        f"--set run.out_dir={OUT}/{name}",
        check=False)
    results[name] = {"rc": rc, "minutes": round((time.time() - t) / 60, 1)}
    print(f"  {name}: exit {rc} in {results[name]['minutes']} min", flush=True)

# ---- result ------------------------------------------------------------
print("\n" + "=" * 64)
print("RESULT  (student = the deployed, observation-only model)")
print("=" * 64, flush=True)
table = {}
for name, meta in results.items():
    hist = pathlib.Path(OUT) / name / "checkpoints" / f"predictor_{TIER}_history.json"
    if not hist.is_file():
        print(f"{name:26} FAILED (no history) {meta['minutes']} min")
        continue
    h = json.loads(hist.read_text())
    # `scores_vs_truth` is the STUDENT. `teacher_scores_vs_truth` sees
    # privileged state and is not a deployable candidate.
    s = h.get("scores_vs_truth") or {}
    table[name] = {"ap": s.get("average_precision"), "auc": s.get("auc"),
                   "base": s.get("positive_rate"), "arch_recorded": h.get("arch")}
    table[name].update(meta)
    print(f"{name:26} AP={table[name]['ap']:.4f} AUC={table[name]['auc']:.4f} "
          f"base={table[name]['base']:.4f} ({meta['minutes']} min)")

(pathlib.Path(OUT) / "summary.json").write_text(json.dumps(table, indent=2))

t_ap = (table.get(f"{TIER}-transformer") or {}).get("ap")
g_ap = (table.get(f"{TIER}-tcn") or {}).get("ap")
print("\n" + "-" * 64)
if t_ap and g_ap:
    print(f"ARCHITECTURE EFFECT (tcn vs transformer): "
          f"{(g_ap - t_ap) / abs(t_ap) * 100:+.1f}% AP")
    print("Same episodes, same windows, same held-out split, same recipe.")
    print("Architecture is the only thing that differs.")
    print()
    print("STOP RULE: tcn is 9.69 ms p99 decision on CPU against a 3.00 ms")
    print("budget, so it passes the deployability gate on GPU only. A win")
    print("here supports 'viable GPU-specific alternative', not a general")
    print("replacement for the production transformer.")
else:
    print("Incomplete: at least one arm produced no model.")
print(f"\nwrote {OUT}/summary.json")
print(f"total {(time.time() - T0) / 60:.1f} min", flush=True)
LOCK.unlink(missing_ok=True)
print("ALLDONE_ARCHCTL")
