#!/usr/bin/env python
"""Did the corpus improve the predictor, or did the architecture?

Every "full corpus improved prediction" number in this project was
quarantined, because the run that produced them moved five things at once: no
``--arch`` was passed, so it silently took the ``gru`` default while the
shipped weights were transformers; ``batch_size`` came from a ``(32, 16, 8)``
ladder that never recorded which rung succeeded; and ``--steps`` and
``teacher_epochs`` were overridden too. Five factors moved, so the effect
belongs to all five jointly and to none of them separately.

This reads the 2x2 that moves exactly two of them and freezes the rest.

The decomposition is only readable if the two corpus effects agree. If
training on the published corpus helps the transformer and hurts the GRU --
or helps one by a little and the other by a lot -- then corpus and
architecture **interact**, and neither has a single main effect worth
quoting. That is a real possible outcome, not a failure of the experiment,
and the report says so rather than averaging over it.

Reads ``summary.json`` written by ``notebooks/deepnote_arch_corpus_2x2.py``;
writes ``reports/arch_corpus_2x2.md``.
"""

from __future__ import annotations

import argparse
import contextlib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

for _stream in (sys.stdout, sys.stderr):
    with contextlib.suppress(AttributeError, ValueError):
        _stream.reconfigure(encoding="utf-8", errors="replace")

REPORTS = REPO_ROOT / "reports"

ARCHS = ("transformer", "gru")
CORPORA = ("seeds", "dataset")

#: Human labels. "seeds" regenerates episodes from the root seed; "dataset"
#: streams the published Kaggle corpus. Both are capped to the same episode
#: count, so the contrast is which episodes rather than how many.
CORPUS_LABEL = {"seeds": "regenerated", "dataset": "published"}


def pct(a: float | None, b: float | None) -> float | None:
    """``b`` against ``a``, as a percentage of ``a``."""
    if not a or not b:
        return None
    return (b - a) / abs(a) * 100


def cell(rows: dict, tier: str, arch: str, corpus: str, field: str = "ap"):
    return (rows.get(f"{tier}-{arch}-{corpus}") or {}).get(field)


def render(rows: dict, tier: str) -> str:
    L: list[str] = []
    A = L.append
    A("# Corpus or architecture? The 2x2")
    A("")
    A("_Generated by `scripts/arch_corpus_report.py` from the run in")
    A("`notebooks/deepnote_arch_corpus_2x2.py`. Student = the deployed,")
    A("observation-only model; the teacher sees privileged state and is not")
    A("what ships._")
    A("")
    A("## What varied, and what was frozen")
    A("")
    A("| | |")
    A("|---|---|")
    A("| **varied** | training corpus (regenerated vs published), architecture |")
    A("| **frozen** | batch size 32 (pinned, not a ladder), epochs, teacher epochs, "
      "episode count, windows per episode, tier, seed, torch build, machine |")
    A("")
    A("Batch size is frozen because it is not a memory setting: retraining one arm")
    A("at 8 instead of 64 moved student AP 0.6915 -> 0.7457, larger than several")
    A("effects this project had credited to the corpus. Episode count is frozen so")
    A("that *corpus* means which episodes rather than how many.")
    A("")
    A("## Student average precision")
    A("")
    A("| corpus | transformer | gru | architecture effect |")
    A("|---|---|---|---|")
    for corpus in CORPORA:
        t = cell(rows, tier, "transformer", corpus)
        g = cell(rows, tier, "gru", corpus)
        d = pct(t, g)
        A(f"| {CORPUS_LABEL[corpus]} | {t:.4f} | {g:.4f} | "
          f"{d:+.1f}% |" if t and g and d is not None
          else f"| {CORPUS_LABEL[corpus]} | "
               f"{t if t else 'missing'} | {g if g else 'missing'} | - |")
    A("")

    eff = {a: pct(cell(rows, tier, a, "seeds"), cell(rows, tier, a, "dataset"))
           for a in ARCHS}
    A("## The corpus effect, per architecture")
    A("")
    A("| architecture | regenerated | published | corpus effect |")
    A("|---|---|---|---|")
    for a in ARCHS:
        s, d = cell(rows, tier, a, "seeds"), cell(rows, tier, a, "dataset")
        A(f"| `{a}` | {s:.4f} | {d:.4f} | {eff[a]:+.1f}% |"
          if s and d and eff[a] is not None
          else f"| `{a}` | {s or 'missing'} | {d or 'missing'} | - |")
    A("")

    A("## Reading")
    A("")
    both = [eff[a] for a in ARCHS if eff[a] is not None]
    if len(both) < 2:
        A("**Incomplete.** At least one arm did not produce a model, so the")
        A("decomposition cannot be read. The quarantine stands.")
    elif both[0] * both[1] < 0:
        A("**Corpus and architecture interact.** The published corpus moves")
        A(f"`{ARCHS[0]}` by {both[0]:+.1f}% and `{ARCHS[1]}` by {both[1]:+.1f}% --")
        A("opposite directions. There is therefore no single \"corpus effect\" to")
        A("quote, and the original claim cannot be rescued by attributing it to")
        A("one factor. Which corpus is better depends on which architecture is")
        A("being trained, so the two must be chosen together.")
    elif max(abs(x) for x in both) > 3 * max(min(abs(x) for x in both), 1e-9):
        A(f"**Same sign, very different size.** {both[0]:+.1f}% against")
        A(f"{both[1]:+.1f}%. The direction transfers across architectures but the")
        A("magnitude does not, so a corpus effect quoted from one architecture")
        A("should not be expected to hold for the other.")
    else:
        A(f"**A corpus effect that transfers.** {both[0]:+.1f}% and")
        A(f"{both[1]:+.1f}% agree in sign and roughly in size, so the corpus")
        A("does have a main effect independent of architecture. This is the")
        A("only outcome under which the original quarantined claim can be")
        A("restated -- and it must be restated at *this* magnitude, measured")
        A("with the recipe frozen, not at the magnitude the confounded run")
        A("reported.")
    A("")
    A("Whatever the sign, the number the confounded run published cannot be")
    A("recovered: its batch rung was never recorded, so that run is not")
    A("reproducible even in principle. See")
    A("[`evidence_status.md`](evidence_status.md).")
    A("")
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--json", default=str(REPORTS / "arch_corpus_2x2.json"))
    ap.add_argument("--tier", default="medium")
    ap.add_argument("--out", default=str(REPORTS / "arch_corpus_2x2.md"))
    args = ap.parse_args()

    src = Path(args.json)
    if not src.is_file():
        raise SystemExit(
            f"no results at {src}. Fetch summary.json from the Deepnote run's "
            f"/work/arch_corpus_2x2_{args.tier}/ first.")
    text = render(json.loads(src.read_text(encoding="utf-8")), args.tier)
    Path(args.out).write_text(text, encoding="utf-8")
    print(text)
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
