#!/usr/bin/env python
"""Can the winning architecture actually meet the dwell budget?

The architecture control found the GRU ahead of the transformer by about 9%
average precision ([arch_control.md](../reports/arch_control.md)). That
settles which model predicts better. It does not settle which model can be
deployed, and those are different questions with different answers here.

The receiver decides once per dwell. `reports/latency_budget.json` measures
the whole decision at a budget of `(t_settle + 1) x dt`, and the predictor
already sits at **1.5x headroom** on MEDIUM -- median 1.369 ms, p99 2.031 ms
against 3.0 ms. That measurement was taken with the shipped transformer. A
1.5x margin does not survive an architecture that is several times slower.

There is a structural reason to expect exactly that. A GRU is recurrent: it
must step through all `W` window slots in sequence, and the steps cannot be
parallelised. A transformer attends over the window in one shot. The GRU is
the *smaller* model -- 0.93 MB against 1.31 MB -- and can still be far slower
per forward pass, because parameter count is not what the dwell budget
constrains.

This times the forward pass alone, which is the part that differs. Latency
depends on architecture and input shape, not on what the weights contain, so
untrained models give the same answer as trained ones and no checkpoint is
needed. Batch 1, because a receiver decides for one dwell at a time -- timing
a batch would measure throughput, which is not the constraint.
"""

from __future__ import annotations

import argparse
import contextlib
import json
import statistics
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

for _stream in (sys.stdout, sys.stderr):
    with contextlib.suppress(AttributeError, ValueError):
        _stream.reconfigure(encoding="utf-8", errors="replace")

ARCHS = ("transformer", "gru", "tcn")


def time_arch(arch: str, cfg, device: str, n: int, warmup: int) -> dict:
    """Median and tail latency of one forward pass, in milliseconds."""
    import torch

    from smartscan.agents.predictors import build_predictor

    model = build_predictor(cfg, arch).to(device).eval()
    n_params = sum(p.numel() for p in model.parameters())
    w = cfg.predictor.window_slots
    b = cfg.n_channels
    x = torch.zeros(1, 4, b, w, device=device)

    samples: list[float] = []
    with torch.no_grad():
        for i in range(warmup + n):
            if device == "cuda":
                torch.cuda.synchronize()
            t0 = time.perf_counter()
            model(x)
            # Without this the CPU returns before the kernel finishes and the
            # number measures launch overhead rather than the forward pass.
            if device == "cuda":
                torch.cuda.synchronize()
            dt = (time.perf_counter() - t0) * 1000.0
            if i >= warmup:
                samples.append(dt)

    samples.sort()
    return {
        "arch": arch,
        "params": n_params,
        "median_ms": statistics.median(samples),
        "p95_ms": samples[int(0.95 * len(samples)) - 1],
        "p99_ms": samples[int(0.99 * len(samples)) - 1],
        "device": device,
    }


def render(rep: dict) -> str:
    L: list[str] = []
    A = L.append
    A("# Does the better predictor fit the dwell budget?")
    A("")
    A("_Generated by `scripts/arch_latency.py`. Forward pass only, batch 1, "
      f"{rep['n']} timed calls on **{rep['device']}**._")
    A("")
    A(f"Budget: `(t_settle + 1) x dt` = **{rep['budget_ms']:.2f} ms** on "
      f"{rep['tier']}. The whole decision must fit, and the forward pass is "
      "only part of it -- belief update and argmax are on top.")
    A("")
    A("| device | architecture | params | median | p95 | p99 | forward alone vs budget |")
    A("|---|---|---|---|---|---|---|")
    for r in rep["archs"]:
        share = r["p99_ms"] / rep["budget_ms"] * 100
        flag = "" if share < 100 else "  **over budget**"
        A(f"| {r['device']} | `{r['arch']}` | {r['params']:,} | "
          f"{r['median_ms']:.3f} ms | {r['p95_ms']:.3f} ms | "
          f"{r['p99_ms']:.3f} ms | {share:.0f}%{flag} |")
    A("")

    worst = rep["archs"][0]["device"]
    by = {r["arch"]: r for r in rep["archs"] if r["device"] == worst}
    t, g = by.get("transformer"), by.get("gru")
    if t and g:
        ratio = g["p99_ms"] / t["p99_ms"] if t["p99_ms"] else float("inf")
        A("## Reading")
        A("")
        A(f"The GRU's p99 forward pass is **{ratio:.1f}x** the transformer's, "
          f"on {g['params'] / t['params'] * 100:.0f}% of the parameters. "
          "Parameter count is not what the dwell budget constrains: a GRU "
          "steps through the window sequentially and a transformer does not.")
        A("")
        if ratio > 1.5:
            A("**This is a deployment constraint, not a detail.** The shipped "
              "predictor already sits at 1.5x headroom on MEDIUM (p99 2.031 ms "
              "against 3.0 ms) *with the transformer*. Multiplying the forward "
              "pass by this factor does not fit, so the ~9% average-precision "
              "advantage cannot be taken without either a faster inference "
              "path or a larger budget.")
        else:
            A("**The GRU fits.** Its latency advantage or penalty is small "
              "enough that the accuracy result decides, and the shipping "
              "recommendation stands on the architecture control alone.")
    A("")
    A("Measured on this machine's device; a receiver's target hardware will "
      "differ. What transfers is the *ratio* between architectures, not the "
      "absolute milliseconds.")
    A("")
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--tier", default="medium")
    ap.add_argument("--n", type=int, default=200)
    ap.add_argument("--warmup", type=int, default=30)
    ap.add_argument("--device", default="both",
                    help="cpu | cuda | both (default: both)")
    ap.add_argument("--out", default=str(REPO_ROOT / "reports" / "arch_latency"))
    args = ap.parse_args()

    from smartscan.config import load_config

    try:
        import torch
    except ImportError:
        raise SystemExit("torch is required for this benchmark") from None

    cfg = load_config(f"{args.tier}.yaml")
    device = args.device or ("cuda" if torch.cuda.is_available() else "cpu")
    dt_ms = cfg.time.dt_s * 1000.0
    budget_ms = (cfg.receiver.t_settle_slots + 1) * dt_ms

    devices = ([d for d in ("cpu", "cuda") if d == "cpu" or torch.cuda.is_available()]
               if args.device == "both" else [device])
    rows = [time_arch(a, cfg, d, args.n, args.warmup)
            for d in devices for a in ARCHS]
    rep = {"tier": args.tier, "device": "+".join(devices), "n": args.n,
           "budget_ms": budget_ms, "archs": rows}

    stem = Path(args.out)
    stem.with_suffix(".json").write_text(json.dumps(rep, indent=2), encoding="utf-8")
    text = render(rep)
    stem.with_suffix(".md").write_text(text, encoding="utf-8")
    print(text)
    print(f"wrote {stem}.md and {stem}.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
