#!/usr/bin/env python
"""What is actually inside each checkpoint, regardless of what it is called.

Three separate confounds in this repository trace to the same root cause: a
checkpoint's identity lived in its filename, and nothing ever checked it.

* ``predictor_hard.pt`` was replaced in place by a differently-trained model.
  The evaluation that followed compared it against itself and reported
  ``+0.0%`` on every metric -- which reads as a null result, not as the
  plumbing fault it was. It was caught only because exact zeros are
  impossible.
* The retraining run changed architecture *and* training corpus together,
  because the training cell never pinned ``--arch``. Every "full corpus"
  improvement is really "full corpus **and** GRU instead of transformer", and
  neither factor can be separated after the fact.
* Fifteen checkpoint files accumulated across four directories with names like
  ``_default``, ``_shipped``, ``_fullcorpus`` and ``_20260202``, none of which
  the loader could verify.

This script answers the question the filenames cannot, by reading each file:
which architecture, which training corpus, and -- via SHA-1 -- which files are
literally the same bytes under different names. Duplicate hashes are the
finding, not an aside: identical hashes under two names are exactly the
condition that makes a self-comparison look like a null result.

Checkpoints written before provenance existed report ``unknown`` rather than
raising. Refusing to describe them would disable the check precisely where the
history is least trustworthy.
"""

from __future__ import annotations

import argparse
import contextlib
import sys
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

for _stream in (sys.stdout, sys.stderr):
    with contextlib.suppress(AttributeError, ValueError):
        _stream.reconfigure(encoding="utf-8", errors="replace")


def scan(root: Path, pattern: str = "predictor*.pt") -> list[dict]:
    """Describe every checkpoint under ``root``, newest path order."""
    from smartscan.agents.predictors import describe_checkpoint

    out = []
    for p in sorted(root.rglob(pattern)):
        if ".git" in p.parts:
            continue
        d = describe_checkpoint(p)
        d["rel"] = p.relative_to(root).as_posix()
        out.append(d)
    return out


def duplicates(rows: list[dict]) -> dict[str, list[str]]:
    """Group paths by content hash, keeping only the genuine collisions."""
    by: dict[str, list[str]] = defaultdict(list)
    for r in rows:
        if r.get("sha1"):
            by[r["sha1"]].append(r["rel"])
    return {h: v for h, v in by.items() if len(v) > 1}


def _licence(a: str, b: str, factor: str = "training_corpus") -> str:
    """Why this pair may or may not be compared for ``factor``."""
    from smartscan.agents.predictors import (
        IncomparableCheckpointsError,
        assert_comparable,
    )

    try:
        diff = assert_comparable(REPO_ROOT / a, REPO_ROOT / b, target_factor=factor,
                                 ignore=("dataset_hash",))
    except IncomparableCheckpointsError as exc:
        msg = str(exc)
        if " -- " in msg:
            msg = msg.split(" -- ", 1)[1].split(". ", 1)[0]
        elif "same bytes" in msg:
            msg = "same bytes: comparing a model against itself"
        else:
            msg = msg.split(" -- ", 1)[0]
        return f"**blocked** -- {msg}"
    return f"licensed for `{factor}` ({diff or 'identical on that factor too'})"


def render(rows: list[dict], dups: dict[str, list[str]]) -> str:
    L: list[str] = []
    A = L.append
    A("# What is actually in each checkpoint")
    A("")
    A("_Generated by `scripts/checkpoint_inventory.py`. Read from the files, not")
    A("from their names._")
    A("")
    A("| file | architecture | corpus | MB | sha1 |")
    A("|---|---|---|---|---|")
    for r in rows:
        A(f"| `{r['rel']}` | {r.get('architecture', '?')} | "
          f"{r.get('training_corpus', '_unrecorded_')} | "
          f"{r.get('bytes', 0) / 1e6:.2f} | `{r.get('sha1', '-')}` |")
    A("")
    if dups:
        A("## Files that are the same bytes under different names")
        A("")
        A("An evaluation that loads two of these as though they were different")
        A("models compares a model against itself. That returns exactly `+0.0%`,")
        A("which is indistinguishable from a real null result unless the hashes")
        A("are checked.")
        A("")
        for h, paths in sorted(dups.items()):
            A(f"- `{h}` -- " + ", ".join(f"`{p}`" for p in paths))
        A("")
    A("## Which comparisons are licensed")
    A("")
    A("A pair is licensed for a factor only if every other recorded factor")
    A("agrees. Pairs are checked with `assert_comparable`, so this is the same")
    A("rule the test suite enforces -- not a description of it.")
    A("")
    for tier in ("easy", "medium", "hard"):
        # One representative per distinct model: identical bytes under three
        # names are one model, and listing all nine pairings would bury the
        # finding in noise.
        uniq: dict[str, dict] = {}
        for r in rows:
            if tier in Path(r["rel"]).name:
                uniq.setdefault(r.get("sha1", r["rel"]), r)
        same = list(uniq.values())
        if len(same) < 2:
            A(f"- **{tier}**: only one distinct model, nothing to compare")
            continue
        for i, a in enumerate(same):
            for b in same[i + 1:]:
                A(f"- `{a['rel']}` vs `{b['rel']}`: "
                  f"{_licence(a['rel'], b['rel'])}")
    A("")
    archs = {r.get("architecture") for r in rows}
    if len(archs) > 1:
        A("## More than one architecture is present")
        A("")
        A(f"Architectures found: {', '.join(sorted(str(a) for a in archs))}. Any")
        A("comparison that crosses this boundary varies architecture in addition")
        A("to whatever it intended to vary, and the two cannot be separated")
        A("afterwards.")
        A("")
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", default=str(REPO_ROOT))
    ap.add_argument("--out", default=str(REPO_ROOT / "reports" / "checkpoints.md"))
    ap.add_argument("--strict", action="store_true",
                    help="exit non-zero if duplicate-content checkpoints exist")
    args = ap.parse_args()

    rows = scan(Path(args.root))
    if not rows:
        print("no checkpoints found")
        return 0
    dups = duplicates(rows)
    text = render(rows, dups)
    Path(args.out).write_text(text, encoding="utf-8")
    print(text)
    print(f"wrote {args.out}")
    return 1 if (args.strict and dups) else 0


if __name__ == "__main__":
    raise SystemExit(main())
