#!/usr/bin/env python
"""Who does a coverage constraint help, and who does it just tax?

``CoverageGate`` enforces a bound on the largest revisit gap: if a channel has
gone unvisited that long the receiver goes there, and only otherwise does the
policy choose. Applying it to one policy and finding an improvement would say
very little. Applying it to five, across four deadlines, says something.

The result is that the gate is **not** a general improvement. Its value tracks
how concentrated the ungated policy already was, and for policies that already
alternate between exploring and exploiting it is pure cost:

* **Rescued.** ``predictor`` parks on channels it is confident about and
  starves its own future reward; forcing it back across the band trades 11.7%
  of intercept time for 77.3% more interception rate. ``epsilon_greedy`` parks
  far worse -- its ungated median time to first intercept is 1.97 s -- and a
  tight gate recovers 92.4% of that and 46 emitters.
* **Marginally helped.** ``whittle`` already balances, so the gate buys 15.7%
  of rate for 34.7% of time.
* **Taxed.** ``phase_locked`` gives up 41.7% of intercept time for 3.8% of
  rate. ``phased`` is worse on *all three* metrics at the loosest deadline: it
  already hands over from sweeping to exploiting on its own, so a gate is
  redundant and only adds retunes.

That last row is the informative one. Phasing and gating are two mechanisms
for the same thing, and they are substitutes rather than complements -- so an
adaptive controller should be built on top of one of them, not both.

Reads ``reports/coverage_gate.json`` (produced by the sweep); writes
``reports/coverage_gate.md``.
"""

from __future__ import annotations

import argparse
import contextlib
import json
import sys
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

for _stream in (sys.stdout, sys.stderr):
    with contextlib.suppress(AttributeError, ValueError):
        _stream.reconfigure(encoding="utf-8", errors="replace")

REPORTS = REPO_ROOT / "reports"

#: Ordered most-concentrated first, which is also most-helped first.
POLICIES = ("predictor", "epsilon_greedy", "whittle", "phase_locked", "phased")
GATES = (1200, 600, 300)


def _delta(base: dict, arm: dict) -> tuple[float, float, int, int]:
    """(Δ intercept time %, Δ rate %, Δ emitters found, mean vetoes)."""
    bt, bw = np.nanmedian(base["ttfi"]), np.nanmedian(base["twir"])
    dt = (bt - np.nanmedian(arm["ttfi"])) / bt * 100
    dw = (np.nanmedian(arm["twir"]) - bw) / bw * 100
    dn = sum(base["never"]) - sum(arm["never"])
    return dt, dw, dn, int(np.mean(arm["vetoes"]))


def classify(dt: float, dw: float, dn: int) -> str:
    """Label an arm by whether the constraint paid for itself."""
    gains = sum(x > 0 for x in (dt, dw, dn))
    if max(dt, dw) > 40 or (gains == 3):
        return "**rescued**"
    if gains >= 2 or max(dt, dw) > 10:
        return "helped"
    if gains == 0:
        return "**harmed**"
    return "taxed"


def render(d: dict) -> str:
    L: list[str] = []
    A = L.append
    A("# Who does a coverage constraint help?")
    A("")
    A("_Generated by `scripts/coverage_gate_report.py`. HARD, 10 paired seeds._")
    A("")
    A("`CoverageGate` bounds the largest revisit gap: past the deadline the receiver")
    A("goes to the most overdue window, otherwise the policy chooses. Positive numbers")
    A("are improvements over the same policy ungated.")
    A("")
    A("| policy | deadline | intercept time | interception rate | emitters found | vetoes | |")
    A("|---|---|---|---|---|---|---|")
    for p in POLICIES:
        base = d.get(f"{p}|0")
        if not base:
            continue
        for g in GATES:
            arm = d.get(f"{p}|{g}")
            if not arm:
                continue
            dt, dw, dn, ve = _delta(base, arm)
            A(f"| `{p}` | {g} | {dt:+.1f}% | {dw:+.1f}% | {dn:+d} | {ve} | "
              f"{classify(dt, dw, dn)} |")
    A("")
    A("## The constraint is not a general improvement")
    A("")
    A("Its value tracks how concentrated the ungated policy already was.")
    A("")
    A("- **`predictor`** parks on channels it is confident about and starves its own")
    A("  future reward. Forcing it back across the band trades **11.7% of intercept")
    A("  time for 77.3% more interception rate** -- a Pareto trade on the two")
    A("  objectives the problem statement names, not a domination.")
    A("- **`epsilon_greedy`** parks far worse: its ungated median time to first")
    A("  intercept is **1.97 s**. A tight deadline recovers **92.4%** of that and")
    A("  **46 emitters**, paying 31.6% of rate.")
    A("- **`whittle`** already balances, so the gate buys 15.7% of rate for 34.7% of")
    A("  time.")
    A("- **`phase_locked`** gives up **41.7% of intercept time for 3.8% of rate**.")
    A("- **`phased`** is worse on *all three* metrics at the loosest deadline.")
    A("")
    A("## Why `phased` being harmed is the informative row")
    A("")
    A("`phased` already hands over from sweeping to exploiting when discovery stalls.")
    A("A gate on top is redundant -- it enforces something the policy is doing")
    A("already -- and the only thing it adds is retunes. Phasing and gating are two")
    A("mechanisms for the same job and they are **substitutes, not complements**, so")
    A("an adaptive exploration controller should be built on one of them rather than")
    A("stacked on both.")
    A("")
    A("## The deadline has a sweet spot, and it moves with the policy")
    A("")
    A("`predictor` peaks at 1200 and is over-constrained at 300, where its rate falls")
    A("back to ungated while intercept time keeps degrading. `whittle` prefers 300,")
    A("where it reaches its best coverage without losing the rate gain. A single")
    A("global constant is therefore wrong in two ways at once: across environments,")
    A("and across policies. That is the argument for replacing the fixed deadline")
    A("with an exploration debt the controller estimates, rather than for tuning the")
    A("constant harder.")
    A("")
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--json", default=str(REPORTS / "coverage_gate.json"))
    ap.add_argument("--out", default=str(REPORTS / "coverage_gate.md"))
    args = ap.parse_args()

    src = Path(args.json)
    if not src.is_file():
        raise SystemExit(f"no sweep results at {src}")
    text = render(json.loads(src.read_text(encoding="utf-8")))
    Path(args.out).write_text(text, encoding="utf-8")
    print(text)
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
