#!/usr/bin/env python
"""Was the predictor improvement volume, architecture, or their interaction?

The quarantined claim was that training on the full corpus improved
prediction. The architecture control has since shown that a large part of
that was architecture: the retraining run omitted ``--arch``, silently took
the config default and switched transformer to GRU while also changing the
corpus, and the GRU predicts about 9% better under a frozen recipe
([arch_control.md](../reports/arch_control.md)).

What remains unmeasured is the corpus contribution itself, and one earlier
attempt at it was invalid for a reason worth stating plainly, because this
script exists to avoid repeating it.

**Every arm must be scored on one held-out set.** The training code splits
whatever data it was given, so two arms trained on different amounts of data
validate on *different* held-out sets, and their average precisions are then
not one measurement. The previous corpus comparison failed exactly there: one
arm validated on ``split(0.8)`` of its own episodes and the other on a
separate 178-episode corpus split, with a different replay trace, class
balancing and validation stride. Comparing those numbers would have produced
a "corpus effect" that was really corpus plus pipeline plus sampler plus
evaluation set.

So this builds the evaluation set **once**, from seeds no arm trains on, and
scores every checkpoint against it afterwards. Training-time validation is
ignored entirely.

The corpus axis is *volume*, not provenance. ``build_report.json`` shows the
published corpus was generated by this same repository from the same
generator, so "published" against "regenerated" is a different draw from one
distribution rather than a different distribution. The variable that actually
differed in the original claim was how many episodes -- 3000 against roughly
40 -- and that is what varies here.

The GRU arms are **explanatory controls, not production candidates**. The GRU
fails the per-dwell latency gate on both CPU and GPU
([arch_latency.md](../reports/arch_latency.md)); it is included only to test
whether volume and architecture interact.
"""

from __future__ import annotations

import argparse
import contextlib
import json
import sys
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

for _stream in (sys.stdout, sys.stderr):
    with contextlib.suppress(AttributeError, ValueError):
        _stream.reconfigure(encoding="utf-8", errors="replace")

REPORTS = REPO_ROOT / "reports"

#: Seeds reserved for evaluation. Disjoint from every training range by
#: construction -- training draws from `run.seed + 2000` upward, so a block
#: far above it cannot be reached however many episodes an arm is given.
HELDOUT_SEEDS = tuple(range(900_000, 900_040))


def heldout_set(cfg, max_windows: int = 200):
    """Build the one evaluation set every arm is scored against.

    Args:
        cfg: Resolved config.
        max_windows: Windows per held-out episode.

    Returns:
        A ``PredictorDataset`` over :data:`HELDOUT_SEEDS`.
    """
    from smartscan.agents.predictors import build_windows

    return build_windows(cfg, list(HELDOUT_SEEDS),
                         max_windows_per_episode=max_windows)


def score_checkpoint(path: Path, cfg, dataset, torch) -> dict:
    """Score one checkpoint on the shared held-out set.

    Scores the **student** path only: the teacher sees privileged state and is
    not deployable, so its numbers would flatter every arm equally and mean
    nothing about what ships.
    """
    from smartscan.agents.predictors import load_predictor_checkpoint
    from smartscan.analysis.metrics import prediction_scores

    model = load_predictor_checkpoint(cfg, path, torch).eval()
    probs, truth = [], []
    with torch.no_grad():
        for i in range(0, len(dataset), 64):
            xb = torch.as_tensor(dataset.x[i:i + 64], dtype=torch.float32)
            probs.append(torch.sigmoid(model(xb)).cpu().numpy())
            truth.append(dataset.y_true[i:i + 64])
    return prediction_scores(np.concatenate(truth), np.concatenate(probs))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--checkpoints", nargs="+", required=True,
                    help="arm=path pairs, e.g. tfm-40=out/a.pt tfm-400=out/b.pt")
    ap.add_argument("--tier", default="medium")
    ap.add_argument("--max-windows", type=int, default=200)
    ap.add_argument("--out", default=str(REPORTS / "volume_control"))
    args = ap.parse_args()

    try:
        import torch
    except ImportError:
        raise SystemExit("torch is required") from None
    from smartscan.config import load_config

    cfg = load_config(f"{args.tier}.yaml")
    print(f"building the shared held-out set from {len(HELDOUT_SEEDS)} "
          f"reserved seeds...", flush=True)
    ds = heldout_set(cfg, args.max_windows)
    print(f"  {len(ds)} held-out windows, base rate "
          f"{float(np.mean(ds.y_true)):.6f}", flush=True)

    rows = {}
    for spec in args.checkpoints:
        if "=" not in spec:
            raise SystemExit(f"expected arm=path, got {spec!r}")
        arm, path = spec.split("=", 1)
        p = Path(path)
        if not p.is_file():
            print(f"  {arm}: MISSING {p}")
            continue
        from smartscan.agents.predictors import describe_checkpoint
        meta = describe_checkpoint(p)
        s = score_checkpoint(p, cfg, ds, torch)
        rows[arm] = {"ap": s["average_precision"], "auc": s["auc"],
                     "base": s["positive_rate"],
                     "arch": meta.get("architecture"),
                     "sha1": meta.get("sha1")}
        print(f"  {arm:16} arch={rows[arm]['arch']:12} "
              f"AP={rows[arm]['ap']:.4f} AUC={rows[arm]['auc']:.4f}", flush=True)

    stem = Path(args.out)
    stem.with_suffix(".json").write_text(
        json.dumps({"tier": args.tier, "heldout_windows": len(ds),
                    "heldout_seeds": list(HELDOUT_SEEDS), "arms": rows},
                   indent=2), encoding="utf-8")
    print(f"\nwrote {stem}.json")
    print("Every arm above was scored on the SAME held-out set, so these "
          "average precisions are one measurement.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
